const countries = [
  { country: "Bangladesh", code: "BDT", symbol: "৳", flag: "🇧🇩" },
  { country: "United States", code: "USD", symbol: "$", flag: "🇺🇸" },
  { country: "United Kingdom", code: "GBP", symbol: "£", flag: "🇬🇧" },
  { country: "Eurozone", code: "EUR", symbol: "€", flag: "🇪🇺" },
  { country: "India", code: "INR", symbol: "₹", flag: "🇮🇳" },
  { country: "Pakistan", code: "PKR", symbol: "₨", flag: "🇵🇰" },
  { country: "Nepal", code: "NPR", symbol: "₨", flag: "🇳🇵" },
  { country: "Bhutan", code: "BTN", symbol: "Nu.", flag: "🇧🇹" },
  { country: "Sri Lanka", code: "LKR", symbol: "Rs", flag: "🇱🇰" },
  { country: "China", code: "CNY", symbol: "¥", flag: "🇨🇳" },
  { country: "Japan", code: "JPY", symbol: "¥", flag: "🇯🇵" },
  { country: "South Korea", code: "KRW", symbol: "₩", flag: "🇰🇷" },
  { country: "Singapore", code: "SGD", symbol: "S$", flag: "🇸🇬" },
  { country: "Malaysia", code: "MYR", symbol: "RM", flag: "🇲🇾" },
  { country: "Thailand", code: "THB", symbol: "฿", flag: "🇹🇭" },
  { country: "Indonesia", code: "IDR", symbol: "Rp", flag: "🇮🇩" },
  { country: "Philippines", code: "PHP", symbol: "₱", flag: "🇵🇭" },
  { country: "Vietnam", code: "VND", symbol: "₫", flag: "🇻🇳" },
  { country: "Hong Kong", code: "HKD", symbol: "HK$", flag: "🇭🇰" },
  { country: "Taiwan", code: "TWD", symbol: "NT$", flag: "🇹🇼" },
  { country: "Australia", code: "AUD", symbol: "A$", flag: "🇦🇺" },
  { country: "New Zealand", code: "NZD", symbol: "NZ$", flag: "🇳🇿" },
  { country: "Canada", code: "CAD", symbol: "C$", flag: "🇨🇦" },
  { country: "Mexico", code: "MXN", symbol: "$", flag: "🇲🇽" },
  { country: "Brazil", code: "BRL", symbol: "R$", flag: "🇧🇷" },
  { country: "Argentina", code: "ARS", symbol: "$", flag: "🇦🇷" },
  { country: "Chile", code: "CLP", symbol: "$", flag: "🇨🇱" },
  { country: "Colombia", code: "COP", symbol: "$", flag: "🇨🇴" },
  { country: "Peru", code: "PEN", symbol: "S/", flag: "🇵🇪" },
  { country: "South Africa", code: "ZAR", symbol: "R", flag: "🇿🇦" },
  { country: "Nigeria", code: "NGN", symbol: "₦", flag: "🇳🇬" },
  { country: "Kenya", code: "KES", symbol: "KSh", flag: "🇰🇪" },
  { country: "Uganda", code: "UGX", symbol: "USh", flag: "🇺🇬" },
  { country: "Tanzania", code: "TZS", symbol: "TSh", flag: "🇹🇿" },
  { country: "Egypt", code: "EGP", symbol: "E£", flag: "🇪🇬" },
  { country: "Morocco", code: "MAD", symbol: "MAD", flag: "🇲🇦" },
  { country: "Tunisia", code: "TND", symbol: "DT", flag: "🇹🇳" },
  { country: "Saudi Arabia", code: "SAR", symbol: "﷼", flag: "🇸🇦" },
  { country: "United Arab Emirates", code: "AED", symbol: "د.إ", flag: "🇦🇪" },
  { country: "Qatar", code: "QAR", symbol: "QR", flag: "🇶🇦" },
  { country: "Kuwait", code: "KWD", symbol: "KD", flag: "🇰🇼" },
  { country: "Bahrain", code: "BHD", symbol: ".د.ب", flag: "🇧🇭" },
  { country: "Oman", code: "OMR", symbol: "﷼", flag: "🇴🇲" },
  { country: "Turkey", code: "TRY", symbol: "₺", flag: "🇹🇷" },
  { country: "Russia", code: "RUB", symbol: "₽", flag: "🇷🇺" },
  { country: "Ukraine", code: "UAH", symbol: "₴", flag: "🇺🇦" },
  { country: "Poland", code: "PLN", symbol: "zł", flag: "🇵🇱" },
  { country: "Czech Republic", code: "CZK", symbol: "Kč", flag: "🇨🇿" },
  { country: "Romania", code: "RON", symbol: "lei", flag: "🇷🇴" },
  { country: "Hungary", code: "HUF", symbol: "Ft", flag: "🇭🇺" },
  { country: "Sweden", code: "SEK", symbol: "kr", flag: "🇸🇪" },
  { country: "Norway", code: "NOK", symbol: "kr", flag: "🇳🇴" },
  { country: "Denmark", code: "DKK", symbol: "kr", flag: "🇩🇰" },
  { country: "Switzerland", code: "CHF", symbol: "CHF", flag: "🇨🇭" }
];
